### ISSUE TITLE
2020H1 GT:NH sprint

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#10]
Mobs Sprint
Bee balancing/new bees
Quest Sprint
Minor Sprint

2020H1 GT:NH sprint
- Review Battlegear commit
- Release additional debug messages/rebase on top of Repo's work
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4316 - Fix battery buffer reporting
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4206 - Fix cleanroom structure detection
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/3145 - LCE not reporting maintenance status
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4043 - Fix miner boundaries
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2888 - Forestry Butterflies
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3366 - Rework graves spawning
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4909 - Add dim exclusion to IFU
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4546 - Implement chunkloading tickets for GT5u machines
- [ ] Add notes to LV quests with Twilight Forest requirements to get started looking there.
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2167 - Issue with Plasma turbine
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4048 - Update small boiler tooltip
- [x] Do quick pass over quests, make sure they are using the correct machine block for the quest icon
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4174 - Update hand prospector to using electricity like the soldering iron.
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4156 - Blazereed/tearstalks nerfing
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3705 - Fix fluids
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2398 - Check out OpenBlocks, see about forking
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3051 - Add custom villager trades
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3974 - Fix party rewards for BQ
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3219 - Add new features to BQ
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4167 - Nerf multiblock oil pump
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/5163 - Shift-clicking lag
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4063 - Add SP field boundaries.
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4368 - Update SP ore output
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4112 - Update plasma turbine tooltip
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4412 - Buff solar boilers
- [x] https://github.com/GTNewHorizons/NewHorizons/issues/4883 - HP solar boiler GUI issue

Slush pile
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4748 - Add HP solar boiler quest
- [ ] Replace all Tier XxX entries with more descriptors to locate which type of tier it is referencing.  Power tier 4, planet tier 3, base defense tier 3, etc.  Make sure unlock quests are easy to understand, and document which quests are needed to unlock which tabs.
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/4201 - Finish migrating wiki page. Priority for next official release.
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2269 - Find a way to control/limit lava monsters so they don't steal all the spawns in the Nether. Limit lower than 20 each spawn time, despawn after a time limit, count number per chunk
- [ ] GTNewHorizons/NewHorizons#2176 - Help with choking and ninja mobs
- [ ] GTNewHorizons/NewHorizons#2033 - Lower poison duration, make adjustable
- [ ] GTNewHorizons/NewHorizons#3229 - Options to make infernals scale better.  Make webber less annoying.  Make infernals require LOS before webbing.
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3617 Related to above
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3220 - Evaluate coins rewards
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/3292 - add debug mode switches for GT
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2285 - Horses causing crash when head gets stuck in Forestry hive
- [ ] https://github.com/richardhendricks/GT5-Unofficial/issues/21 - Verify causes of stevescart disappearing
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2523 - IC2 cells not working with AE2
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2479 - fluid filter covers, how do they work?
- [ ] https://github.com/GTNewHorizons/NewHorizons/issues/2388 - Update Galacticraft and Galacticspace so that the rockets only use rocket fuel, not fuel.
- [ ] https://github.com/draknyte1/GTplusplus/issues/180 - Check on GT++ multiblock functionality
- [ ] GTNewHorizons/NewHorizons#2162 - Galacticraft torch issue with battlegear slots

**Comment by richardhendricks** [comment]
Check out why myFTB.de  is having problems with waypoints disappearing

**Comment by draknyte1** [comment]
The final issue related to WailaHarvestability & the IC2 'issue' (It's 100% how it's implemented by the devs) are fixed by me in https://github.com/draknyte1/GTplusplus/commit/caa09ffe94f23c1383f2f8259876de6c88a637de
